/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sudokuproject.sudokuworldsaga.ui.SudokuBoard;

/**
 *
 * @author Henri
 */
public class SudokuPanelSubset extends javax.swing.JPanel {

    private SudokuCell[] cells;
    
    /**
     * Creates new form SudokuPanel
     */
    public SudokuPanelSubset() {
        initComponents();
        cells = new SudokuCell[]{cell1, cell2, cell3, cell4, cell5, cell6, cell7, cell8, cell9};
    }

    public void setValue(int i, String value) {
        cells[i].setValue(value);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cell1 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell();
        cell2 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell();
        cell3 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell();
        cell4 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell();
        cell5 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell();
        cell6 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell();
        cell7 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell();
        cell8 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell();
        cell9 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setLayout(new java.awt.GridLayout(3, 3, 1, 1));
        add(cell1);
        add(cell2);
        add(cell3);
        add(cell4);
        add(cell5);
        add(cell6);
        add(cell7);
        add(cell8);
        add(cell9);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell cell1;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell cell2;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell cell3;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell cell4;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell cell5;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell cell6;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell cell7;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell cell8;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuCell cell9;
    // End of variables declaration//GEN-END:variables
}
