/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sudokuproject.sudokuworldsaga.ui.SudokuBoard;

import java.awt.Color;
import sudokuproject.sudokuworldsaga.domain.Sudoku;

/**
 *
 * @author Henri
 */
public class SudokuPanel extends javax.swing.JPanel {

    private SudokuPanelSubset[] subsets;
    /**
     * Creates new form test
     */
    public SudokuPanel() {
        initComponents();
        subsets = new SudokuPanelSubset[]{subset1, subset2, subset3, subset4, subset5, subset6, subset7, subset8, subset9};
    }

    public void updateValues(Sudoku sudoku) {
        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {
                setXY(i, j, sudoku.getXY(i,j) + "");
                setXYColor(i, j, Color.WHITE);
            }
        }
    }
    
    public void setXY(int x, int y, String value) {
        subsets[findSubsetIndex(x, y)].setValue(findCellIndex(x, y), value);
    }
    
    public void setXYColor(int x, int y, Color color) {
        subsets[findSubsetIndex(x, y)].setColor(findCellIndex(x, y), color);
    }
    
    private int findSubsetIndex(int x, int y) {
        int rowFactor = ((y + 1) - y % 3) / 3;
        int columnFactor = ((x + 1) - x % 3) / 3;
        return columnFactor + 3 * rowFactor;
    }
    
    private int findCellIndex(int x, int y) {
        int row = y % 3;
        int col = x % 3;
        return col + 3 * row;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subset1 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset();
        subset2 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset();
        subset3 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset();
        subset4 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset();
        subset5 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset();
        subset6 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset();
        subset7 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset();
        subset8 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset();
        subset9 = new sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(3, 3, 1, 1));
        add(subset1);
        add(subset2);
        add(subset3);
        add(subset4);
        add(subset5);
        add(subset6);
        add(subset7);
        add(subset8);
        add(subset9);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset subset1;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset subset2;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset subset3;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset subset4;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset subset5;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset subset6;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset subset7;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset subset8;
    private sudokuproject.sudokuworldsaga.ui.SudokuBoard.SudokuPanelSubset subset9;
    // End of variables declaration//GEN-END:variables


}
