package sudokuproject.sudokuworldsaga.SudokuBoard;

/**
 * The graphical representation of a single sudoku cell.
 *
 * @author Henri
 */
public class SudokuCell extends javax.swing.JPanel {

    /**
     * Creates new form SudokuCell
     */
    public SudokuCell() {
        initComponents();
    }
    
    /** 
     * Sets the value of the cell as param newValue. If newValue == "0" then the cell value is set to "".
     * 
     * @param newValue 
     */
    public void setValue(String newValue) {
        if (newValue == null) {
            return;
        }
        try {
            int val = Integer.parseInt(newValue);
            if (val < 0 || val > 9) {
                return;
            }
        } catch (NumberFormatException ex) {
           return;
        }
        if (newValue.equals("0")) {
            cellValue.setText("");
        } else {
            cellValue.setText(newValue);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cellValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        setMaximumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(10, 10));
        setLayout(new java.awt.GridLayout(1, 0));

        cellValue.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cellValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cellValue.setAlignmentX(0.5F);
        cellValue.setMaximumSize(new java.awt.Dimension(10, 10));
        cellValue.setMinimumSize(new java.awt.Dimension(10, 10));
        cellValue.setPreferredSize(new java.awt.Dimension(10, 10));
        add(cellValue);
        cellValue.getAccessibleContext().setAccessibleName("sudokuCellValue");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cellValue;
    // End of variables declaration//GEN-END:variables
}
