package sudokuproject.sudokuworldsaga.guicomponents;

import java.awt.Color;

/**
 * SudokuPanelSubset is the graphical representation of a 3x3 subset of the sudoku board.
 *
 * @author Henri
 */
public class SudokuPanelSubset extends javax.swing.JPanel {

    private SudokuCell[] cells;
    
    /**
     * Creates new form SudokuPanel
     */
    public SudokuPanelSubset() {
        initComponents();
        cells = new SudokuCell[]{cell1, cell2, cell3, cell4, cell5, cell6, cell7, cell8, cell9};
    }
    
    private boolean notInRange(int i, int lower, int upper) {
        if (i < lower || i > upper) {
            return true;
        }
        return false;
    }

    /**
     * Changes the value of cell i to param value.
     * 
     * @param i the nth cell in the subset 
     * @param value new value
     */
    public void setValue(int i, String value) {
        if (notInRange(i, 0, 8)) {
            return;
        }
        cells[i].setValue(value);
    }
    
    /**
     * Changes the color of cell i to param cell.
     * 
     * @param i the nth cell in the subset 
     * @param color new color
     */
    public void setColor(int i, Color color) {
        if (notInRange(i, 0, 8)) {
            return;
        }
        cells[i].setBackground(color);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cell1 = new sudokuproject.sudokuworldsaga.guicomponents.SudokuCell();
        cell2 = new sudokuproject.sudokuworldsaga.guicomponents.SudokuCell();
        cell3 = new sudokuproject.sudokuworldsaga.guicomponents.SudokuCell();
        cell4 = new sudokuproject.sudokuworldsaga.guicomponents.SudokuCell();
        cell5 = new sudokuproject.sudokuworldsaga.guicomponents.SudokuCell();
        cell6 = new sudokuproject.sudokuworldsaga.guicomponents.SudokuCell();
        cell7 = new sudokuproject.sudokuworldsaga.guicomponents.SudokuCell();
        cell8 = new sudokuproject.sudokuworldsaga.guicomponents.SudokuCell();
        cell9 = new sudokuproject.sudokuworldsaga.guicomponents.SudokuCell();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setLayout(new java.awt.GridLayout(3, 3, 1, 1));
        add(cell1);
        cell1.getAccessibleContext().setAccessibleName("cell0");

        add(cell2);
        cell2.getAccessibleContext().setAccessibleName("cell1");

        add(cell3);
        cell3.getAccessibleContext().setAccessibleName("cell2");

        add(cell4);
        cell4.getAccessibleContext().setAccessibleName("cell3");

        add(cell5);
        cell5.getAccessibleContext().setAccessibleName("cell4");

        add(cell6);
        cell6.getAccessibleContext().setAccessibleName("cell5");

        add(cell7);
        cell7.getAccessibleContext().setAccessibleName("cell6");

        add(cell8);
        cell8.getAccessibleContext().setAccessibleName("cell7");

        add(cell9);
        cell9.getAccessibleContext().setAccessibleName("cell8");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sudokuproject.sudokuworldsaga.guicomponents.SudokuCell cell1;
    private sudokuproject.sudokuworldsaga.guicomponents.SudokuCell cell2;
    private sudokuproject.sudokuworldsaga.guicomponents.SudokuCell cell3;
    private sudokuproject.sudokuworldsaga.guicomponents.SudokuCell cell4;
    private sudokuproject.sudokuworldsaga.guicomponents.SudokuCell cell5;
    private sudokuproject.sudokuworldsaga.guicomponents.SudokuCell cell6;
    private sudokuproject.sudokuworldsaga.guicomponents.SudokuCell cell7;
    private sudokuproject.sudokuworldsaga.guicomponents.SudokuCell cell8;
    private sudokuproject.sudokuworldsaga.guicomponents.SudokuCell cell9;
    // End of variables declaration//GEN-END:variables


}
