/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sudokuproject.sudokuworldsaga.ui;

import java.io.File;
import javax.swing.JFileChooser;
import sudokuproject.sudokuworldsaga.domain.Sudoku;
import sudokuproject.sudokuworldsaga.domain.SudokuGenerator;
import sudokuproject.sudokuworldsaga.domain.SudokuSolver;
import sudokuproject.sudokuworldsaga.fileio.FileManager;

/**
 *
 * @author Henri
 * 
 * TEST GUI GENERATED BY NETBEANS IDE 
 * PROOF OF CONCEPT > > NOT FINAL
 * 
 */
public class SudokuWorldSaga extends javax.swing.JFrame {

    private Sudoku sudoku;
    private JFileChooser fc = new JFileChooser();
    
    /**
     * Creates new form GameGUIManager
     */
    public SudokuWorldSaga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        sudokuBoardBorder = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sudokuArea = new javax.swing.JTextArea();
        newSudokuButton = new javax.swing.JButton();
        loadSudokuButton = new javax.swing.JButton();
        solveButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        newUnsolvedSudokuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku Game");
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);

        sudokuBoardBorder.setBackground(new java.awt.Color(255, 255, 255));
        sudokuBoardBorder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 5));
        sudokuBoardBorder.setPreferredSize(new java.awt.Dimension(350, 350));

        sudokuArea.setEditable(false);
        sudokuArea.setColumns(20);
        sudokuArea.setRows(5);
        jScrollPane1.setViewportView(sudokuArea);

        javax.swing.GroupLayout sudokuBoardBorderLayout = new javax.swing.GroupLayout(sudokuBoardBorder);
        sudokuBoardBorder.setLayout(sudokuBoardBorderLayout);
        sudokuBoardBorderLayout.setHorizontalGroup(
            sudokuBoardBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sudokuBoardBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        sudokuBoardBorderLayout.setVerticalGroup(
            sudokuBoardBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sudokuBoardBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        newSudokuButton.setBackground(new java.awt.Color(0, 0, 0));
        newSudokuButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        newSudokuButton.setForeground(new java.awt.Color(255, 255, 255));
        newSudokuButton.setText("New Empty");
        newSudokuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSudokuButtonActionPerformed(evt);
            }
        });

        loadSudokuButton.setBackground(new java.awt.Color(0, 0, 0));
        loadSudokuButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loadSudokuButton.setForeground(new java.awt.Color(255, 255, 255));
        loadSudokuButton.setText("Load Sudoku");
        loadSudokuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSudokuButtonActionPerformed(evt);
            }
        });

        solveButton.setBackground(new java.awt.Color(0, 0, 0));
        solveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        solveButton.setForeground(new java.awt.Color(255, 255, 255));
        solveButton.setText("Solve Sudoku");
        solveButton.setEnabled(false);
        solveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveButtonActionPerformed(evt);
            }
        });

        jPanel1.setMinimumSize(new java.awt.Dimension(350, 127));
        jPanel1.setLayout(new java.awt.GridLayout(5, 3));

        newUnsolvedSudokuButton.setBackground(new java.awt.Color(0, 0, 0));
        newUnsolvedSudokuButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        newUnsolvedSudokuButton.setForeground(new java.awt.Color(255, 255, 255));
        newUnsolvedSudokuButton.setText("New Unsolved");
        newUnsolvedSudokuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUnsolvedSudokuButtonActionPerformed(evt);
                newUnsolvedSudokuButtonActionPerformed1(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sudokuBoardBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newUnsolvedSudokuButton)
                    .addComponent(newSudokuButton)
                    .addComponent(solveButton)
                    .addComponent(loadSudokuButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {loadSudokuButton, newSudokuButton, solveButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(solveButton)
                        .addGap(20, 20, 20)
                        .addComponent(loadSudokuButton)
                        .addGap(20, 20, 20)
                        .addComponent(newUnsolvedSudokuButton)
                        .addGap(20, 20, 20)
                        .addComponent(newSudokuButton))
                    .addComponent(sudokuBoardBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveButtonActionPerformed
        // TODO add your handling code here:
        sudoku = SudokuSolver.solve(sudoku);
        sudokuArea.setText(sudoku.toString());
        solveButton.setEnabled(false);
    }//GEN-LAST:event_solveButtonActionPerformed

    private void newSudokuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSudokuButtonActionPerformed
        // TODO add your handling code here:
        sudoku = new Sudoku(3,3);
        sudokuArea.setText(sudoku.toString());
        solveButton.setEnabled(true);
    }//GEN-LAST:event_newSudokuButtonActionPerformed

    private void loadSudokuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSudokuButtonActionPerformed
        sudokuArea.setText("Opening");
        int returnVal = fc.showOpenDialog(SudokuWorldSaga.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            sudoku = FileManager.loadSudokuFromFile(file);
            if (sudoku != null) {
                sudokuArea.setText("Opening:\n" + file.getName() + "\n");
                sudokuArea.append(sudoku.toString());
                solveButton.setEnabled(true);
            }
            else {
                sudokuArea.setText("Failed to load.");
            }
        }
        else {
            sudokuArea.setText("Open command canceled by user.\n");
        }
    }//GEN-LAST:event_loadSudokuButtonActionPerformed

    private void newUnsolvedSudokuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUnsolvedSudokuButtonActionPerformed
        // TODO add your handling code here:
        sudoku = SudokuGenerator.genNewSudoku(3, 3, 50);
        sudokuArea.setText(sudoku.toString());
        solveButton.setEnabled(true);
    }//GEN-LAST:event_newUnsolvedSudokuButtonActionPerformed

    private void newUnsolvedSudokuButtonActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUnsolvedSudokuButtonActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_newUnsolvedSudokuButtonActionPerformed1

    /**
     * Launches the GUI
     */
    
    
    public static void launch() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SudokuWorldSaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SudokuWorldSaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SudokuWorldSaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SudokuWorldSaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokuWorldSaga().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadSudokuButton;
    private javax.swing.JButton newSudokuButton;
    private javax.swing.JButton newUnsolvedSudokuButton;
    private javax.swing.JButton solveButton;
    private javax.swing.JTextArea sudokuArea;
    private javax.swing.JPanel sudokuBoardBorder;
    // End of variables declaration//GEN-END:variables
}
